name: Sync Upstream

# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '1 18 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: Andrey1994/sync-upstream-repo@0.0.2
        with: 
          upstream_repo: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt # change this
          upstream_branch: master # change this
          downstream_branch: master # change this
          token: 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
