name: Sync Upstream

on:
  workflow_dispatch:
  schedule: 
  - cron: "0 13 * * 1"
          
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: https://github.com/hassio-zigbee2mqtt
          upstream_branch: master
          downstream_branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
          
